name: quran_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get: ^3.17.1
  get_storage: null
  shimmer: ^1.1.2
  fluttertoast: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  freezed: ^0.12.2
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/al-quran.jpg
    - lib/infrastructure/data/surah-info.json
    - lib/infrastructure/data/daily-doa.json
    - lib/infrastructure/data/asmaul-husna.json
    - lib/infrastructure/data/surah/1.json
    - lib/infrastructure/data/surah/2.json
    - lib/infrastructure/data/surah/3.json
    - lib/infrastructure/data/surah/4.json
    - lib/infrastructure/data/surah/5.json
    - lib/infrastructure/data/surah/6.json
    - lib/infrastructure/data/surah/7.json
    - lib/infrastructure/data/surah/8.json
    - lib/infrastructure/data/surah/9.json
    - lib/infrastructure/data/surah/10.json
    - lib/infrastructure/data/surah/11.json
    - lib/infrastructure/data/surah/12.json
    - lib/infrastructure/data/surah/13.json
    - lib/infrastructure/data/surah/14.json
    - lib/infrastructure/data/surah/15.json
    - lib/infrastructure/data/surah/16.json
    - lib/infrastructure/data/surah/17.json
    - lib/infrastructure/data/surah/18.json
    - lib/infrastructure/data/surah/19.json
    - lib/infrastructure/data/surah/20.json
    - lib/infrastructure/data/surah/21.json
    - lib/infrastructure/data/surah/22.json
    - lib/infrastructure/data/surah/23.json
    - lib/infrastructure/data/surah/24.json
    - lib/infrastructure/data/surah/25.json
    - lib/infrastructure/data/surah/26.json
    - lib/infrastructure/data/surah/27.json
    - lib/infrastructure/data/surah/28.json
    - lib/infrastructure/data/surah/29.json
    - lib/infrastructure/data/surah/30.json
    - lib/infrastructure/data/surah/31.json
    - lib/infrastructure/data/surah/32.json
    - lib/infrastructure/data/surah/33.json
    - lib/infrastructure/data/surah/34.json
    - lib/infrastructure/data/surah/35.json
    - lib/infrastructure/data/surah/36.json
    - lib/infrastructure/data/surah/37.json
    - lib/infrastructure/data/surah/38.json
    - lib/infrastructure/data/surah/39.json
    - lib/infrastructure/data/surah/40.json
    - lib/infrastructure/data/surah/41.json
    - lib/infrastructure/data/surah/42.json
    - lib/infrastructure/data/surah/43.json
    - lib/infrastructure/data/surah/44.json
    - lib/infrastructure/data/surah/45.json
    - lib/infrastructure/data/surah/46.json
    - lib/infrastructure/data/surah/47.json
    - lib/infrastructure/data/surah/48.json
    - lib/infrastructure/data/surah/49.json
    - lib/infrastructure/data/surah/50.json
    - lib/infrastructure/data/surah/51.json
    - lib/infrastructure/data/surah/52.json
    - lib/infrastructure/data/surah/53.json
    - lib/infrastructure/data/surah/54.json
    - lib/infrastructure/data/surah/55.json
    - lib/infrastructure/data/surah/56.json
    - lib/infrastructure/data/surah/57.json
    - lib/infrastructure/data/surah/58.json
    - lib/infrastructure/data/surah/59.json
    - lib/infrastructure/data/surah/60.json
    - lib/infrastructure/data/surah/61.json
    - lib/infrastructure/data/surah/62.json
    - lib/infrastructure/data/surah/63.json
    - lib/infrastructure/data/surah/64.json
    - lib/infrastructure/data/surah/65.json
    - lib/infrastructure/data/surah/66.json
    - lib/infrastructure/data/surah/67.json
    - lib/infrastructure/data/surah/68.json
    - lib/infrastructure/data/surah/69.json
    - lib/infrastructure/data/surah/70.json
    - lib/infrastructure/data/surah/71.json
    - lib/infrastructure/data/surah/72.json
    - lib/infrastructure/data/surah/73.json
    - lib/infrastructure/data/surah/74.json
    - lib/infrastructure/data/surah/75.json
    - lib/infrastructure/data/surah/76.json
    - lib/infrastructure/data/surah/77.json
    - lib/infrastructure/data/surah/78.json
    - lib/infrastructure/data/surah/79.json
    - lib/infrastructure/data/surah/80.json
    - lib/infrastructure/data/surah/81.json
    - lib/infrastructure/data/surah/82.json
    - lib/infrastructure/data/surah/83.json
    - lib/infrastructure/data/surah/84.json
    - lib/infrastructure/data/surah/85.json
    - lib/infrastructure/data/surah/86.json
    - lib/infrastructure/data/surah/87.json
    - lib/infrastructure/data/surah/88.json
    - lib/infrastructure/data/surah/89.json
    - lib/infrastructure/data/surah/90.json
    - lib/infrastructure/data/surah/91.json
    - lib/infrastructure/data/surah/92.json
    - lib/infrastructure/data/surah/93.json
    - lib/infrastructure/data/surah/94.json
    - lib/infrastructure/data/surah/95.json
    - lib/infrastructure/data/surah/96.json
    - lib/infrastructure/data/surah/97.json
    - lib/infrastructure/data/surah/98.json
    - lib/infrastructure/data/surah/99.json
    - lib/infrastructure/data/surah/100.json
    - lib/infrastructure/data/surah/101.json
    - lib/infrastructure/data/surah/102.json
    - lib/infrastructure/data/surah/103.json
    - lib/infrastructure/data/surah/104.json
    - lib/infrastructure/data/surah/105.json
    - lib/infrastructure/data/surah/106.json
    - lib/infrastructure/data/surah/107.json
    - lib/infrastructure/data/surah/108.json
    - lib/infrastructure/data/surah/109.json
    - lib/infrastructure/data/surah/110.json
    - lib/infrastructure/data/surah/111.json
    - lib/infrastructure/data/surah/112.json
    - lib/infrastructure/data/surah/113.json
    - lib/infrastructure/data/surah/114.json

  fonts:
    - family: LPMQ
      fonts:
        - asset: assets/fonts/LPMQ IsepMisbah.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
